version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout

      - run:
          name: Instalar validadores
          command: |
            npm install -g html-validator-cli stylelint stylelint-config-standard

      - run:
          name: Validar HTML
          command: |
            html-validator --file index.html --verbose

      - run:
          name: Validar CSS
          command: |
            stylelint "**/*.css"

workflows:
  version: 2
  validate_site:
    jobs:
      - validate
