version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout

      - run:
          name: Instalar validadores
          command: |
            npm install -g html-validator-cli stylelint stylelint-config-standard

      - run:
          name: Validar HTML
          command: |
            echo "Validando archivos HTML..."
            for file in *.html; do
              echo "âž¡ Validando $file"
              html-validator --file "$file" --verbose || exit 1
            done

      - run:
          name: Validar CSS
          command: |
            echo "Validando archivos CSS..."
            stylelint "**/*.css"

workflows:
  validate_site:
    jobs:
      - validate
